version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: mscds
      POSTGRES_PASSWORD: Admin@123
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env

volumes:
  pgdata:
